name: Create Tag

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch: # This allows manual triggering

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Determine Branch
        id: branch
        run: |
          branch=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          echo "branch=${branch}" >> $GITHUB_OUTPUT

      - name: Check if PR is merged
        id: pr-merged
        run: echo "is_merged=${{ github.event.pull_request.merged }}" >> $GITHUB_OUTPUT

      - name: Determine Tag
        id: tag_suffix
        run: |
          if [[ "${{ steps.branch.outputs.branch }}" == "development" ]]; then
            echo "tag_suffix=-dev" >> $GITHUB_OUTPUT
          else
            echo "tag_suffix="  >> $GITHUB_OUTPUT
          fi

      - name: Extract version
        id: version
        run: |
          version=$(grep -o '".*"' taggy/version.py | tr -d '"')
          echo "version=${version}${{ steps.tag_suffix.outputs.tag_suffix }}" >> $GITHUB_OUTPUT

      - name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.pr-merged.outputs.is_merged == 'true' && steps.branch.output.branch == 'main'
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
