name: Create Tag on Merge

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt  # Replace with your actual requirements file if applicable

      - name: Extract version
        id: version
        run: |
          version=$(python -c "from pingpong import __version__; print(__version__)")
          echo "::set-output name=version::$version"

      - name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
