name: Create Tag on Merge

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch: # This allows manual triggering

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt  # Replace with your actual requirements file if applicable

      - name: Check if PR is merged
        id: pr-merged
        run: echo "::set-output name=is_merged::${{ github.event.pull_request.merged }}"

      - name: Extract version
        id: version
        run: |
          # version=$(python -c "from pingpong import __version__; print(__version__)")
          version=$(grep -o '".*"' pingpong/version.py | tr -d '"')
          echo "::set-output name=version::$version"

      - name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.pr-merged.outputs.is_merged == 'true' || github.event_name == 'push'
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
